# Generated by Django 2.2.5 on 2019-09-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='온도')),
                ('humidity', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='습도')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='측정시간')),
            ],
            options={
                'verbose_name': '스마트 홈 데이터',
                'verbose_name_plural': '스마트 홈 데이터',
                'db_table': 'Uleung_HomeInfo',
            },
        ),
    ]
