# Generated by Django 2.2.5 on 2019-09-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uleung', '0006_homeinfo_aircontem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='androidrequested',
            old_name='airconTempUpDwon',
            new_name='airconTempUpDown',
        ),
    ]
