# Generated by Django 2.2.5 on 2019-09-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uleung', '0007_auto_20190927_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinfo',
            name='humidity',
        ),
    ]
