# Generated by Django 2.2.5 on 2019-09-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uleung', '0008_remove_homeinfo_humidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledRed', models.IntegerField(verbose_name='led Red value')),
                ('ledGreen', models.IntegerField(verbose_name='led green value')),
                ('ledBlue', models.IntegerField(verbose_name='led blue value')),
                ('airconThreshold', models.IntegerField(verbose_name='AirConditioner Temperature setting')),
                ('ledThreshold', models.IntegerField(verbose_name='LED light setting')),
            ],
            options={
                'verbose_name': '안드로이드 setting 데이터',
                'verbose_name_plural': '안드로이드 setting 데이터',
                'db_table': 'Uleung_settings',
            },
        ),
    ]
