# Generated by Django 2.2.5 on 2019-09-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uleung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='androidRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvOnOff', models.IntegerField(verbose_name='TV on off')),
                ('airconOnOff', models.IntegerField(verbose_name='AirConditioner on off')),
                ('airconTempUp', models.IntegerField(verbose_name='AirConditioner Temperature Up')),
                ('airconTempDown', models.IntegerField(verbose_name='AirConditioner Temperature Down')),
            ],
        ),
    ]
