# Generated by Django 2.2.5 on 2019-09-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uleung', '0002_androidrequested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='androidrequested',
            options={'verbose_name': '안드로이드 요청 데이터', 'verbose_name_plural': '안드로이드 요청 데이터'},
        ),
        migrations.AlterModelTable(
            name='androidrequested',
            table='Uleung_androidRequested',
        ),
    ]
