# Generated by Django 2.2.5 on 2019-09-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uleung', '0003_auto_20190920_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='습도'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='온도'),
        ),
    ]
