# Generated by Django 2.2.5 on 2019-09-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uleung', '0004_auto_20190922_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidrequested',
            name='airconTempDown',
        ),
        migrations.RemoveField(
            model_name='androidrequested',
            name='airconTempUp',
        ),
        migrations.AddField(
            model_name='androidrequested',
            name='airconTempUpDwon',
            field=models.IntegerField(default=0, verbose_name='AirConditioner Temperature Up Down'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='androidrequested',
            name='tvChUpDown',
            field=models.IntegerField(default=0, verbose_name='TV Channel Up Down'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='androidrequested',
            name='tvVolUpDown',
            field=models.IntegerField(default=0, verbose_name='TV Volume Up Down'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='light',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='조도'),
            preserve_default=False,
        ),
    ]
