# Generated by Django 2.2.5 on 2019-09-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uleung', '0005_auto_20190927_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='airconTem',
            field=models.IntegerField(default=0, verbose_name='현재 에어컨 설정 온도'),
            preserve_default=False,
        ),
    ]
